### ISSUE TITLE
remove btcd folder

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#103]
Since Simnet doesn't use btcd anymore, this folder should be removed

**Comment by reliveyy** [comment]
I don't think we need to remove unused images' folder. Here is my reasons:
1. I dosen't affect the end users because we do not download images folder to ~/.xud-docker
2. It only provide the whole picture of the docker project. For the normal users it means no hidden piceces. For the developers it provides helpful image building guide. Even if we deleted these folder it still exists in the `.git` folder

**Comment by kilrau** [comment]
I disagree - btcd is not used at all and hence should removed from git & docker, both.
