### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#216]
We ultimately want to have both: start params and a config file. Like most other clients we use. Start params being used for temporary things, config file for permanent things, surviving restarts. Start parameters overwrite config file in case of conflict. If bash of python: python is fine.

**Comment by reliveyy** [comment]
I think we should respect the convention of xud's configuration file type: toml. Then the next question for this issue is that we need a toml parser. There are few options:

1. Using grep/sed/awk to roughly retrieve the configuration entries
2. Using existing command line toml parser, but this may introduce some new dependencies.
3. Writing a toml parser in awk (no existing one according to my google search)
4. Writing a toml parser in bash (very hard!)

**Comment by kilrau** [comment]
I think our new banner features for market makers (https://github.com/ExchangeUnion/xud-docker/issues/30) make a `xud-docker.conf` very desirable. Reasons:
1. market maker can insert answers into conf file, which xud-docker setup will try to find and parse, avoiding being asked all these questions. Also, user can change values (e.g. add litecoin full node) later by simply editing the config file)
2. xud-docker setup uses .conf file to store user answers, once entered. One conf file per xud-docker `data dir`.
