### ISSUE TITLE
Print "Failed to parse config file"

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#252]
It is not clear to the user if the config file was read and parsed without problems. I would add an "Failed to parse config file, ignoring." print if it fails. Nothing on success.

**Comment by kilrau** [comment]
Related: https://github.com/ExchangeUnion/xud-docker/issues/263

**Comment by reliveyy** [comment]
The current implementation will catch `toml.TomlDecodeError` and print whatever `toml` package error says to the screen. I agree sometimes it's hard to tell if the error message is due to a configuration file syntax error or not. So we can improve the error meesages like
```
❌ Syntax error in configuration file ~/.xud-docker/testnet.conf: specific error message hold on toml.TomlDecodeError
```
Or to be simple
```
Failed to parse config file ~/.xud-docker/testnet.conf, ignoring.
```
But the later one is different from the first which is fail-fast. However the later one will keep going with default configuration somehow. I need a further confirmation about this @kilrau

**Comment by kilrau** [comment]
Definitely second message.

`Failed to parse config file ~/.xud-docker/testnet.conf, exiting.`

Should be the message and behavior. User needs to either fix or delete config file to move forward. That's the behavior of bitcoin core / lnd too.
