### ISSUE TITLE
status of XUD shows "Waiting for lndltc, raiden" when their individual states show otherwise

### ISSUE THREAD

**Issue by peartobear** [ExchangeUnion/xud-docker#277]
**Describe the bug**

![Screenshot 2020-01-20 at 8 44 44 PM](https://user-images.githubusercontent.com/44926540/72737503-b638e700-3bc5-11ea-92a1-0bd741abc12a.png)

The status of XUD shows "waiting for LNDLTC, Raiden" when their individual states shows both of them are ready. 

**To Reproduce**

`status` command after setting up and syncing testnet xud environment. 

**Expected behavior**

The status should reflect consistent information.

**Comment by peartobear** [comment]
Fails to fetch status after `restart xud`

![Screenshot 2020-01-20 at 8 49 30 PM](https://user-images.githubusercontent.com/44926540/72737831-5d1d8300-3bc6-11ea-9cb8-25ef0e102a99.png)

**Comment by reliveyy** [comment]
> Fails to fetch status after `restart xud`

Could you attach your xud containers log? `docker logs testnet_xud_1`

**Comment by peartobear** [comment]
@reliveyy logs: https://termbin.com/d8fa

**Comment by reliveyy** [comment]
I guess it's beause our xud:latest image it not built with latest xud master branch. @peartobear

**Comment by reliveyy** [comment]
Could you re-run xud.sh and check if the newly built xud image resolves your problem. @peartobear

**Comment by peartobear** [comment]
I re ran xud.sh and it did not resolve the issue @reliveyy  

[log.pdf](https://github.com/ExchangeUnion/xud-docker/files/4086991/log.pdf)

**Comment by peartobear** [comment]
doing `xud unlock` and putting the master password fixed this issue

**Comment by kilrau** [comment]
Found the same. So it must be calling some xud endpoints that are not available when locked.

**Comment by kilrau** [comment]
I found the reason for this behavior:
- lndbtc/lndltc: status is set by `lncli getinfo` -> which responds and shows they lnd's are synced and ready -> `Ready`
- `xud`: status is set by `xucli getinfo` -> where lndbtc/lndltc status' are stuck with `lnd-xTC is Unlocked` because of https://github.com/ExchangeUnion/xud/issues/1457. So once @sangaman managed to fix https://github.com/ExchangeUnion/xud/issues/1457, the status' should align again. We'll keep this open til to verify.
