### ISSUE TITLE
XUD UI Project

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/xud-docker#656]
Original issue: https://github.com/ExchangeUnion/xud/issues/471.

We want to revive this as a native GUI project for market makers, sitting atop the current xud-docker. The setup UX should be similar to https://lightningpolar.com/, a native GUI connecting to docker in the background:
![image](https://user-images.githubusercontent.com/19181985/89880503-a0702b00-dbc4-11ea-9250-cc7a20e68977.png)

If docker is not installed, it helps installing it. Target platforms:
- macOS
- ubuntu amd64/arch64
- windows 10 amd 64 with docker (using the wsl2 backend)

Step 1: agree on the setup concept (how GUI and xud-docker connect) & tech for the UI to achieve above cross-platform support. xud-docker will remain a CLI-first project just like all other bitcoin/lightning projects out there (meaning some features might be accessible via cli only, never vice versa) since we are optimizing for technical market makers running this on an "unattended" setup. It is also ok for the GUI to use xud-docker specific features. Goal is to run xud-docker under the hood as-is.

Step 2: select GUI features, wireframing, UI design

Step 3: development :tada:

**Comment by peartobear** [comment]
There are three projects we could look for inspiration: [Lightning Polar](https://github.com/jamaljsr/polar), [Sparkswap](https://github.com/sparkswap/sparkswap-desktop), and [Zap Desktop](https://github.com/LN-Zap/zap-desktop). All of these projects use [Electron](https://www.electronjs.org/) with ReactJS for cross platform desktop app support. Additional TypeScript use will help increase productivity. So I propose a generalised tech stack of Electron + ReactJS + TypeScript. The frontend dev could choose either Redux, [ReactN](https://github.com/CharlesStover/reactn), or [Easy Peasy](https://github.com/ctrlplusb/easy-peasy) for local and global state management. In case, React Hooks serves the purpose, third party state management can be discarded. It's important that the app uses Vercel's [Hazel](https://github.com/vercel/hazel) for pushing updates, as there will inevitably be critical hotfixes that would be required on already installed versions. End to end testing with [Jest](https://github.com/facebook/jest), [TestCafe](https://github.com/DevExpress/testcafe), or [Cypress](https://www.cypress.io/) is also recommended before release.

Just like lightning polar, there would be setup dependencies necessary to run the GUI, For windows and Mac - [Docker Desktop](https://www.docker.com/products/docker-desktop) will do the trick. For Linux, [Docker Server](https://docs.docker.com/get-docker/) and [Docker Compose](https://docs.docker.com/compose/install/) will have to be installed separately. 

The GUI will only support the XUD light setup. Since the prod version will deal with mainnet assets, XUD docker needs to be [hardened](https://www.stackrox.com/post/2017/08/hardening-docker-containers-and-hosts-against-vulnerabilities-a-security-toolkit/) with best practices. Just like Lightning Polar, The XUD Docker GUI app will create a docker image from XUD dockerFile, and then build that image. Sparkswap has a similar dockarised [LND engine](https://github.com/sparkswap/lnd-engine) that encapsulates, BTCD, LTCD, and, forked LND-BTC and LND-LTC nodes. They then pull that LND-engine as a [dependency](https://github.com/sparkswap/sparkswap-desktop/blob/master/package.json) on the Electron powered desktop frontend. The architecture and GUI connection logic in our case can be exactly the same. Zap Desktop can be referenced on how to deal with Neutrino, in case that is required.

**Comment by reliveyy** [comment]
I'm look forward to try Electron. @kilrau

**Comment by peartobear** [comment]
@reliveyy check out Vercel's [Hazel](https://github.com/vercel/hazel) as an alternative to autoUpdater. It's super fast and tiniest update server. autoUpdater doesn't support Linux yet.

**Comment by kilrau** [comment]
@peartobear and I started a PRD, keep you posted.

**Comment by kilrau** [comment]
Update: we decided to go for a web-based basic UI for market makers first instead of a standalone UI since the target user for such remains somewhat unclear. Closing here for now.
